/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import dao.ChiTietMTDAO;
import dao.SachDAO;
import java.sql.JDBCType;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import pojo.ChiTietMT;
import pojo.Sach;


/**
 *
 * @author Admin
 */
public class ChiTietMuonTra extends javax.swing.JFrame {
       int g;
    /**
     * Creates new form ChiTietMuonTra
     */
    public ChiTietMuonTra(int s) {
        initComponents();
        this.setTitle("Chi tiết");
        this.setSize(500, 500);
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        btnLuu.setVisible(false);
        btnHuy.setVisible(false);
        lb_ChiTiet.setText("THÔNG TIN CHI TIẾT PHIẾU MƯỢN TRẢ CÓ MÃ: "+s);
        lb_ma.setText(s+"");
        g=s;
        lb_k1.setVisible(false);
        lb_k2.setVisible(false);
        cbo_Sach.setEditable(true);
        AutoCompleteDecorator.decorate(cbo_Sach);
        hienthi();
        
    }
    public ChiTietMuonTra() {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lb_ma = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTienPhat = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lb_ChiTiet = new javax.swing.JLabel();
        btnX = new javax.swing.JButton();
        cbo_Sach = new javax.swing.JComboBox<>();
        lb_k1 = new javax.swing.JLabel();
        lb_k2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Mượn Trả", "Mã Sách", "Tiền phạt", "Ghi chú phạt"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 452, 134);

        jLabel1.setText("Mã:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 220, 22, 16);
        getContentPane().add(lb_ma);
        lb_ma.setBounds(100, 220, 40, 20);

        jLabel3.setText("Mã Sách:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 250, 54, 16);

        jLabel4.setText("Tiền Phạt:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 290, 60, 16);

        txtTienPhat.setText("0");
        txtTienPhat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTienPhatFocusLost(evt);
            }
        });
        getContentPane().add(txtTienPhat);
        txtTienPhat.setBounds(100, 280, 120, 30);

        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });
        getContentPane().add(txtGhiChu);
        txtGhiChu.setBounds(100, 322, 340, 30);

        jLabel5.setText("Ghi Chú:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 330, 50, 16);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem);
        btnThem.setBounds(40, 190, 65, 25);

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        getContentPane().add(btnCapNhat);
        btnCapNhat.setBounds(160, 190, 100, 25);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu);
        btnLuu.setBounds(70, 380, 53, 25);

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuy);
        btnHuy.setBounds(210, 380, 53, 25);
        getContentPane().add(lb_ChiTiet);
        lb_ChiTiet.setBounds(60, 10, 330, 20);

        btnX.setText("Xóa");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });
        getContentPane().add(btnX);
        btnX.setBounds(350, 190, 55, 25);

        getContentPane().add(cbo_Sach);
        cbo_Sach.setBounds(100, 242, 290, 30);

        lb_k1.setForeground(new java.awt.Color(255, 51, 51));
        lb_k1.setText("(*)");
        getContentPane().add(lb_k1);
        lb_k1.setBounds(400, 250, 30, 16);

        lb_k2.setForeground(new java.awt.Color(255, 51, 51));
        lb_k2.setText("(*):Bắt buộc");
        getContentPane().add(lb_k2);
        lb_k2.setBounds(160, 420, 90, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int row=jTable1.getSelectedRow();
        String ma= (String)jTable1.getValueAt(row, 0);
        String mas= (String)jTable1.getValueAt(row, 1);
        ChiTietMT a=ChiTietMTDAO.layCTMT(Integer.parseInt(ma),Integer.parseInt(mas));
        lb_ma.setText(a.getMaMT());
  
        txtTienPhat.setText(a.getTienPhat()+"");
        txtGhiChu.setText(a.getGhiChu());
        Sach c=SachDAO.laySach(Integer.parseInt(mas));
        cbo_Sach.setSelectedItem(c.toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
       
       txtGhiChu.setText("");
       cbo_Sach.setSelectedIndex(-1);
       btnLuu.setVisible(true);
       btnHuy.setVisible(true);
       btnCapNhat.setEnabled(false);
       btnX.setEnabled(false);
       cbo_Sach.setEnabled(true);
       lb_k1.setVisible(true);
       lb_k2.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        
        int tg=cbo_Sach.getSelectedIndex();
        ChiTietMT dg=new ChiTietMT(lb_ma.getText(),cbo_Sach.getItemAt(tg).toString().substring(cbo_Sach.getItemAt(tg).toString().lastIndexOf(':')+1),Integer.parseInt(txtTienPhat.getText()),txtGhiChu.getText());
        int tl=JOptionPane.showConfirmDialog(this, "bn có muốn cập nhật nxb có mã "+lb_ma.getText(), "thông báo", JOptionPane.YES_NO_OPTION);
        if(tl==JOptionPane.YES_OPTION){
            ChiTietMTDAO.capNhatCTMT(dg);
        hienthi(); 
        }
        else return;
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(cbo_Sach.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin bắt buộc");
        }
        else if(txtTienPhat.getText().equals("")){
                int tg=cbo_Sach.getSelectedIndex();
                    if(ChiTietMTDAO.ktTrung(Integer.parseInt(lb_ma.getText()), Integer.parseInt(cbo_Sach.getItemAt(tg).toString().substring(cbo_Sach.getItemAt(tg).toString().lastIndexOf(':')+1)))){
                        JOptionPane.showMessageDialog(this,"thêm thất bại do đã có sách "+cbo_Sach.getItemAt(tg).toString()+" trong phiếu");

                    }
                    else{

                        ChiTietMT dg=new ChiTietMT(lb_ma.getText(),cbo_Sach.getItemAt(tg).toString().substring(0,1),0,txtGhiChu.getText());          
                        ChiTietMTDAO.themCTMT(dg);
                        txtGhiChu.setText("");
                        txtTienPhat.setText("0");
                        cbo_Sach.setSelectedIndex(-1);
                        btnLuu.setVisible(false);
                        btnHuy.setVisible(false);
                        btnCapNhat.setEnabled(true);
                        btnX.setEnabled(true);
                        hienthi();
                        cbo_Sach.setEnabled(false);
                         lb_k1.setVisible(false);
                        lb_k2.setVisible(false);
                        JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                    }
        }
        else{
            int tg=cbo_Sach.getSelectedIndex();
            if(ChiTietMTDAO.ktTrung(Integer.parseInt(lb_ma.getText()), Integer.parseInt(cbo_Sach.getItemAt(tg).toString().substring(cbo_Sach.getItemAt(tg).toString().lastIndexOf(':')+1)))){
                JOptionPane.showMessageDialog(this,"thêm thất bại do đã có sách "+cbo_Sach.getItemAt(tg).toString()+" trong phiếu");

            }
            else{

                ChiTietMT dg=new ChiTietMT(lb_ma.getText(),cbo_Sach.getItemAt(tg).toString().substring(cbo_Sach.getItemAt(tg).toString().lastIndexOf(':')+1),
                        Integer.parseInt(txtTienPhat.getText()),txtGhiChu.getText());          
                ChiTietMTDAO.themCTMT(dg);
                txtGhiChu.setText(""); 
                cbo_Sach.setSelectedIndex(-1);
                btnLuu.setVisible(false);
                btnHuy.setVisible(false);
                btnCapNhat.setEnabled(true);
                btnX.setEnabled(true);
                hienthi();
                cbo_Sach.setEnabled(false);
                 lb_k1.setVisible(false);
                lb_k2.setVisible(false);
                JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            }
        
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        btnCapNhat.setEnabled(true);
        btnX.setEnabled(true);
        btnHuy.setVisible(false);
        btnLuu.setVisible(false);
        txtGhiChu.setText("");
        cbo_Sach.setSelectedIndex(-1);
        txtTienPhat.setText("0");
      cbo_Sach.setEnabled(false);
        lb_ma.setText("");
         lb_k1.setVisible(false);
        lb_k2.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()<1){
             JOptionPane.showMessageDialog(this, "Hãy chọn Dòng muốn xóa");
         }
        else{
                int row=jTable1.getSelectedRow();
            String ma= (String)jTable1.getValueAt(row, 1);

            ChiTietMTDAO.xoaCTMT(g,Integer.parseInt(ma));
            hienthi();
            JOptionPane.showMessageDialog(this, "Xóa Thành Công");
            txtTienPhat.setText("0");
        }

    }//GEN-LAST:event_btnXActionPerformed

    private void txtTienPhatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTienPhatFocusLost
        // TODO add your handling code here:
        if(txtTienPhat.getText().equals("")!=true){
            try{
                
             double a=Double.parseDouble(txtTienPhat.getText());
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền hợp lệ");
                txtTienPhat.requestFocus();
                
            }
        }
    }//GEN-LAST:event_txtTienPhatFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietMuonTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnX;
    private javax.swing.JComboBox<String> cbo_Sach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_ChiTiet;
    private javax.swing.JLabel lb_k1;
    private javax.swing.JLabel lb_k2;
    private javax.swing.JLabel lb_ma;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtTienPhat;
    // End of variables declaration//GEN-END:variables

    private void hienthi() {
       ArrayList<ChiTietMT> a=ChiTietMTDAO.ChiTietMTMa(g);
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        for(ChiTietMT db:a){
            Vector<Object> vec=new Vector<Object>();
            vec.add(db.getMaMT());
            vec.add(db.getMaSH());
       
            vec.add(db.getTienPhat());
            vec.add(db.getGhiChu());
            dtm.addRow(vec);
            
        }
        jTable1.setModel(dtm);
    
        //load cbo Sach
        ArrayList<Sach> dsNXB=SachDAO.layDanhSachSach();
        for(Sach db:dsNXB){

            cbo_Sach.addItem(db.toString());
        }
        cbo_Sach.setSelectedIndex(-1);
        cbo_Sach.setEnabled(false);
    }
    
}
