/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import dao.DocGiaDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.DocGia;

/**
 *
 * @author Admin
 */
public class frDocGia extends javax.swing.JDialog {
    DefaultTableModel dtm;
    String ma;
    /**
     * Creates new form frDocGia
     */
    public frDocGia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Độc Giả");
          this.setLocation(450, 200);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        btnHuy.setVisible(false);
        btnLuu.setVisible(false);
        lb_k1.setVisible(false);
        lb_k2.setVisible(false);
        lb_k3.setVisible(false);
        lb_k5.setVisible(false);
        hienthi();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimDocGia = new javax.swing.JTextField();
        btnTimKiemDocGia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtSLMuon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lb_Ma = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lb_k1 = new javax.swing.JLabel();
        lb_k2 = new javax.swing.JLabel();
        lb_k3 = new javax.swing.JLabel();
        lb_k5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnTimKiemDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_TimKiem.png"))); // NOI18N
        btnTimKiemDocGia.setText("Tìm Kiếm");
        btnTimKiemDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemDocGiaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Độc Giả", "Tên Độc Giả"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setText("THÔNG TIN CHI TIẾT");

        txtSLMuon.setText("0");
        txtSLMuon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSLMuonFocusLost(evt);
            }
        });

        jLabel1.setText("Mã:");

        jLabel2.setText("Tên");

        jLabel3.setText("SDT:");

        jLabel4.setText("Địa chỉ:");

        jLabel5.setText("Số lần mượn:");

        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDTFocusLost(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        lb_k1.setForeground(new java.awt.Color(255, 0, 51));
        lb_k1.setText("(*)");

        lb_k2.setForeground(new java.awt.Color(255, 0, 51));
        lb_k2.setText("(*)");

        lb_k3.setForeground(new java.awt.Color(255, 0, 0));
        lb_k3.setText("(*)");

        lb_k5.setForeground(new java.awt.Color(255, 51, 51));
        lb_k5.setText("(*):Bắt buộc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLuu)
                                .addGap(28, 28, 28)
                                .addComponent(btnCapNhat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(btnHuy))
                            .addComponent(lb_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSLMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_k2))
                            .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(txtDiaChi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_k1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_k3))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lb_k5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lb_k1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_k2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_k3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSLMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addGap(44, 44, 44)
                .addComponent(lb_k5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("DANH SÁCH ĐỘC GIẢ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txtTimDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiemDocGia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnThem)
                        .addGap(119, 119, 119)
                        .addComponent(btnXoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimKiemDocGia)
                            .addComponent(txtTimDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnThem))
                        .addGap(76, 76, 76))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemDocGiaActionPerformed
        // TODO add your handling code here:
         ArrayList<DocGia> dsDG=DocGiaDAO.timKiemDGTheoTen(txtTimDocGia.getText());
        DefaultTableModel atm=(DefaultTableModel)jTable1.getModel();
        atm.setRowCount(0);
        for(DocGia db:dsDG){
            Vector<Object> vec=new Vector<Object>();
            vec.add(db.getMaDG());
            vec.add(db.getTenDG());
            vec.add(db.getSdt());
            vec.add(db.getDiaChi());
            vec.add(db.getSlmuon());
            atm.addRow(vec);
            
        }
        jTable1.setModel(atm);
    }//GEN-LAST:event_btnTimKiemDocGiaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        btnHuy.setVisible(false);
        btnLuu.setVisible(false);
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtSLMuon.setText("0");
        txtTen.setText("");
        lb_Ma.setText("");
        btnCapNhat.setVisible(false);
        btnXoa.setVisible(false);
        btnHuy.setVisible(true);
        btnLuu.setVisible(true);
        lb_k1.setVisible(true);
        lb_k2.setVisible(true);
        lb_k3.setVisible(true);
        lb_k5.setVisible(true);
        
    }//GEN-LAST:event_btnThemActionPerformed

    
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
         
       
        if(txtDiaChi.getText().equals("")||txtSDT.getText().equals("")||txtTen.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin bắt buộc");
         }
        else{
             try{
                  Double a=Double.parseDouble(txtSDT.getText());
                  if(txtSLMuon.getText().equals("")){
                    DocGia dg=new DocGia(txtTen.getText(),txtSDT.getText(),txtDiaChi.getText(),0);    
                    DocGiaDAO.themDG(dg);
                     hienthi();
                     btnHuy.setVisible(false);
                    btnLuu.setVisible(false);
                    txtDiaChi.setText("");
                    txtSDT.setText("");
                    txtSLMuon.setText("0");
                    txtTen.setText("");
                    lb_Ma.setText("");
                    btnCapNhat.setVisible(true);
                    btnXoa.setVisible(true);
                    lb_k1.setVisible(false);
                    lb_k2.setVisible(false);
                    lb_k3.setVisible(false);
                    lb_k5.setVisible(false);
                    JOptionPane.showMessageDialog(this, "Thêm Thành Công");
        
                }
                else{
                    DocGia dg=new DocGia(txtTen.getText(),txtSDT.getText(),txtDiaChi.getText(),Integer.parseInt(txtSLMuon.getText()));    
                    DocGiaDAO.themDG(dg);
                     hienthi();
                     btnHuy.setVisible(false);
                    btnLuu.setVisible(false);
                    txtDiaChi.setText("");
                    txtSDT.setText("");
                    txtSLMuon.setText("0");
                    txtTen.setText("");
                    lb_Ma.setText("");
                    btnCapNhat.setVisible(true);
                    btnXoa.setVisible(true);
                    lb_k1.setVisible(false);
                    lb_k2.setVisible(false);
                    lb_k3.setVisible(false);
                    lb_k5.setVisible(false);
                    JOptionPane.showMessageDialog(this, "Thêm Thành Công");
                }
             }
             catch(Exception ex){
                 JOptionPane.showMessageDialog(this, "SDT Không hợp lệ");
                 txtSDT.requestFocus();
             }
        }
        
        
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        
        
         if(jTable1.getSelectedRowCount()<1){
             JOptionPane.showMessageDialog(this, "Hãy chọn Độc giả muốn xóa");
         }
         else{
                int row=jTable1.getSelectedRow();
                ma= (String)jTable1.getValueAt(row, 0);
              int tl=JOptionPane.showConfirmDialog(null,"bạn muốn xóa phải không","thông báo",JOptionPane.YES_NO_OPTION);
                if(tl==JOptionPane.YES_OPTION){
                    DocGiaDAO.xoaDG(Integer.parseInt(ma));
                    hienthi();
                    JOptionPane.showMessageDialog(this, "Xóa Thành Công");
                    txtSDT.setText("");
                    txtSLMuon.setText("0");
                    txtTen.setText("");
                    txtDiaChi.setText("");
                }
                else{
                    return;
                }
         }
         
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        ma= (String)jTable1.getValueAt(row, 0);
        DocGia a=DocGiaDAO.layDG(Integer.parseInt(ma));
        lb_Ma.setText(a.getMaDG());
        txtTen.setText(a.getTenDG());
        txtSDT.setText(a.getSdt());
        txtDiaChi.setText(a.getDiaChi());
        txtSLMuon.setText(a.getSlmuon()+"");
        new ChiTietMTDG(ma).setVisible(true);


        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        btnHuy.setVisible(false);
        btnLuu.setVisible(false);
        txtDiaChi.setText("");
        txtSDT.setText("");
        txtSLMuon.setText("0");
        txtTen.setText("");
        lb_Ma.setText("");
        btnCapNhat.setVisible(true);
        btnXoa.setVisible(true);
        lb_k1.setVisible(false);
        lb_k2.setVisible(false);
        lb_k3.setVisible(false);
        lb_k5.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if(txtDiaChi.getText().equals("")||txtSDT.getText().equals("")||txtTen.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin bắt buộc");
             
         }
        else{
            try{
                Double a=Double.parseDouble(txtSDT.getText());
                DocGia dg=new DocGia(lb_Ma.getText(),txtTen.getText(),txtSDT.getText(),txtDiaChi.getText(),Integer.parseInt(txtSLMuon.getText()));
                int tl=JOptionPane.showConfirmDialog(this,"bn muốn cập nhật thông tin độc giả có mã "+lb_Ma.getText(),
                        "thông báo", JOptionPane.YES_NO_OPTION);
                if(tl==JOptionPane.YES_OPTION){
               DocGiaDAO.capNhatDG(dg);
               hienthi(); 
            }
            else{
                return;
            }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, "sdt Không hợp lệ");
                txtSDT.requestFocus();
            }
            
        }
        
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSDTFocusLost

    private void txtSLMuonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSLMuonFocusLost
        // TODO add your handling code here:
          
    }//GEN-LAST:event_txtSLMuonFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frDocGia dialog = new frDocGia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiemDocGia;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_Ma;
    private javax.swing.JLabel lb_k1;
    private javax.swing.JLabel lb_k2;
    private javax.swing.JLabel lb_k3;
    private javax.swing.JLabel lb_k5;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSLMuon;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimDocGia;
    // End of variables declaration//GEN-END:variables

    private void hienthi() {
       ArrayList<DocGia> dsDG=DocGiaDAO.layDanhSachDG();
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        for(DocGia db:dsDG){
            Vector<Object> vec=new Vector<Object>();
            vec.add(db.getMaDG());
            vec.add(db.getTenDG());
            dtm.addRow(vec);
            
        }
        jTable1.setModel(dtm);
    }
}
