/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import dao.ChiTietMTDAO;
import dao.DocGiaDAO;
import dao.MuonTraDAO;
import dao.QuanLiDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import pojo.DocGia;
import pojo.MuonTra;
import pojo.QuanLi;
import pojo.Sach;

/**
 *
 * @author Admin
 */
public class frMuonTra extends javax.swing.JDialog {
    String ma;
 String maql;
    /**
     * Creates new form frMuonTra
     */
    public frMuonTra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnLuu.setVisible(false);
        btnHuy.setVisible(false);
        
        hienthi();
        
        
    }
    public frMuonTra(java.awt.Frame parent, boolean modal,String s) {
        super(parent, modal);
        initComponents();
        
        btnLuu.setVisible(false);
        btnHuy.setVisible(false);
        lb_k1.setVisible(false);
        lb_k2.setVisible(false);
        hienthi();
        maql=s;
        cbo_DocGia.setEditable(true);
        AutoCompleteDecorator.decorate(cbo_DocGia);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_ma = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayMuon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaQL = new javax.swing.JLabel();
        cbo_DocGia = new javax.swing.JComboBox<>();
        lb_k1 = new javax.swing.JLabel();
        lb_k2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Mượn Trả", "Mã Độc Giả", "Mã Quãn Lí", "Ngày Mượn", "Ngày Trả"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Mã QL:");

        jLabel5.setText("Ngày Mượn:");

        jLabel1.setText("Mã:");

        jLabel2.setText("Mã DG:");

        jLabel6.setText("THÔNG TIN");

        txtNgayMuon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel8.setText("Ngày Trả:");

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel3.setText("Nhập ngày theo định dạng yyyy-mm-dd");

        lb_k1.setForeground(new java.awt.Color(255, 0, 51));
        lb_k1.setText("(*)");

        lb_k2.setForeground(new java.awt.Color(255, 0, 0));
        lb_k2.setText("(*):Bắt buộc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(btnLuu)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMaQL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCapNhat)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                            .addComponent(btnHuy))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jLabel6))
                        .addComponent(txtNgayTra, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNgayMuon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbo_DocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_k1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lb_k2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_ma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbo_DocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_k1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtMaQL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnCapNhat)
                    .addComponent(btnHuy))
                .addGap(18, 18, 18)
                .addComponent(lb_k2)
                .addContainerGap())
        );

        jLabel7.setText("DANH SÁCH");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(btnXoa)
                        .addGap(129, 129, 129)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa))
                .addGap(0, 55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        ma= (String)jTable1.getValueAt(row, 0);
        ChiTietMuonTra a=new ChiTietMuonTra(Integer.parseInt(ma));
        a.setVisible(true);
        MuonTra b=MuonTraDAO.layMT(Integer.parseInt(ma));
        lb_ma.setText(b.getMaMT());
        QuanLi v=QuanLiDAO.layQL(Integer.parseInt(b.getMaQL()));
        txtMaQL.setText(v.toString());
        txtNgayMuon.setText(b.getNgayMuon());
        txtNgayTra.setText(b.getNgayTra());
         //hiện cbo NXB
        DocGia nxb=DocGiaDAO.layDG(Integer.parseInt(b.getMaDG()));
        cbo_DocGia.setSelectedItem(nxb.toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTable1MouseEntered

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        lb_ma.setText("");
        QuanLi a=QuanLiDAO.layQL(Integer.parseInt(maql));
        txtMaQL.setText(a.toString());
        txtNgayMuon.setText("");
        txtNgayTra.setText("");
        btnLuu.setVisible(true);
       btnHuy.setVisible(true);
       btnCapNhat.setVisible(false);
       btnXoa.setVisible(false);
       cbo_DocGia.setSelectedIndex(-1);
       lb_k1.setVisible(true);
        lb_k2.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
         if(jTable1.getSelectedRowCount()<1){
                JOptionPane.showMessageDialog(this,"hãy chọn Phiếu muốn xóa!");
                
        }
        else if(ChiTietMTDAO.ktChiTietMTTheoMaMT(Integer.parseInt((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0)))){
                JOptionPane.showMessageDialog(this, "Xóa không thành công do có chi tiết phiếu nhập tham chiếu đến");
                return;
        }
        else{
                int row=jTable1.getSelectedRow();
               String ma= (String)jTable1.getValueAt(row, 0);
        
                int tl=JOptionPane.showConfirmDialog(null,"bạn muốn xóa phải không","thông báo",JOptionPane.YES_NO_OPTION);
                  if(tl==JOptionPane.YES_OPTION){
                       MuonTraDAO.xoaMT(Integer.parseInt(ma));
                       JOptionPane.showMessageDialog(this,"Xóa thành công");
                      hienthi();
                      txtNgayMuon.setText("");
                      txtNgayTra.setText("");
                }
                else{
                    
                   return;
                
                }
         }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(cbo_DocGia.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông rin bắt buộc!");
        }
        else{
            int tg=cbo_DocGia.getSelectedIndex();
            if(txtNgayMuon.getText().equals("")){
                MuonTra dg=new MuonTra(cbo_DocGia.getItemAt(tg).toString().substring(cbo_DocGia.getItemAt(tg).toString().lastIndexOf(':')+1),
                        txtMaQL.getText().substring(txtMaQL.getText().lastIndexOf(':')+1),txtNgayMuon.getText(),txtNgayTra.getText());
                MuonTraDAO.themMTKoNgayMuon(dg);
            }
            else if(txtNgayTra.getText().equals("")){
                MuonTra dg=new MuonTra(cbo_DocGia.getItemAt(tg).toString().substring(cbo_DocGia.getItemAt(tg).toString().lastIndexOf(':')+1),
                        txtMaQL.getText().substring(txtMaQL.getText().lastIndexOf(':')+1),txtNgayMuon.getText(),txtNgayTra.getText());
                MuonTraDAO.themMT(dg);
            }
            else{
                MuonTra dg=new MuonTra(cbo_DocGia.getItemAt(tg).toString().substring(cbo_DocGia.getItemAt(tg).toString().lastIndexOf(':')+1),
                        txtMaQL.getText().substring(txtMaQL.getText().lastIndexOf(':')+1),txtNgayMuon.getText(),txtNgayTra.getText());


                MuonTraDAO.themMTCoNgayTra(dg);
            }

            cbo_DocGia.setSelectedIndex(-1);
            lb_ma.setText("");
            txtMaQL.setText(""); 
            txtNgayMuon.setText(""); 
            txtNgayTra.setText("");
            btnLuu.setVisible(false);
            btnHuy.setVisible(false);
            btnCapNhat.setVisible(true);
            btnXoa.setVisible(true);
            hienthi();
            lb_k1.setVisible(false);
            lb_k2.setVisible(false);
        }
        
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        int tg=cbo_DocGia.getSelectedIndex();
        if(txtNgayTra.getText().equals("")){
            MuonTra dg=new MuonTra(lb_ma.getText(),cbo_DocGia.getItemAt(tg).toString().substring(cbo_DocGia.getItemAt(tg).toString().lastIndexOf(':')+1),
                    txtMaQL.getText().substring(txtMaQL.getText().lastIndexOf(':')+1),txtNgayMuon.getText(),txtNgayTra.getText());
            int tl=JOptionPane.showConfirmDialog(this, "bn có muốn cập nhật nxb có mã "+lb_ma.getText(), "thông báo", JOptionPane.YES_NO_OPTION);
            if(tl==JOptionPane.YES_OPTION){
                MuonTraDAO.capNhatMT(dg);
            hienthi();
            //sau khi cập nhật vẫn hiện ĐỘC GIẢ
             DocGia a=DocGiaDAO.layDG(Integer.parseInt(cbo_DocGia.getItemAt(tg).toString().substring(cbo_DocGia.getItemAt(tg).toString().lastIndexOf(':')+1)));
            int t2=Integer.parseInt(a.getMaDG());
            DocGia  x2=DocGiaDAO.layDG(t2);
            cbo_DocGia.setSelectedItem(x2.toString());
            }
            else return;
        }
        else{
            MuonTra dg=new MuonTra(lb_ma.getText(),cbo_DocGia.getItemAt(tg).toString().substring(cbo_DocGia.getItemAt(tg).toString().lastIndexOf(':')+1),
                    txtMaQL.getText().substring(txtMaQL.getText().lastIndexOf(':')+1),txtNgayMuon.getText(),txtNgayTra.getText());
            int tl=JOptionPane.showConfirmDialog(this, "bn có muốn cập nhật nxb có mã "+lb_ma.getText(), "thông báo", JOptionPane.YES_NO_OPTION);
            if(tl==JOptionPane.YES_OPTION){
                MuonTraDAO.capNhatMTCoNgayTra(dg);
            hienthi(); 
            //sau khi cập nhật vẫn hiện ĐỘC GIẢ
             DocGia a=DocGiaDAO.layDG(Integer.parseInt(cbo_DocGia.getItemAt(tg).toString().substring(0,1)));
            int t2=Integer.parseInt(a.getMaDG());
            DocGia  x2=DocGiaDAO.layDG(t2);
            cbo_DocGia.setSelectedItem(x2.toString());
            }
            else return;
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        btnCapNhat.setVisible(true);
        btnXoa.setVisible(true);
        btnHuy.setVisible(false);
        btnLuu.setVisible(false);
        cbo_DocGia.setSelectedIndex(-1);
        txtMaQL.setText("");
        txtNgayMuon.setText("");
        txtNgayTra.setText("");
        lb_ma.setText("");
        lb_k1.setVisible(false);
        lb_k2.setVisible(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frMuonTra dialog = new frMuonTra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbo_DocGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_k1;
    private javax.swing.JLabel lb_k2;
    private javax.swing.JLabel lb_ma;
    private javax.swing.JLabel txtMaQL;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNgayTra;
    // End of variables declaration//GEN-END:variables

    private void hienthi() {
       ArrayList<MuonTra> a=MuonTraDAO.layDanhSachMuonTra();
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        this.setLocation(450, 300);
        dtm.setRowCount(0);
        for(MuonTra db:a){
            Vector<Object> vec=new Vector<Object>();
            vec.add(db.getMaMT());
            vec.add(db.getMaDG());
            vec.add(db.getMaQL());
            vec.add(db.getNgayMuon());
            vec.add(db.getNgayTra());
            dtm.addRow(vec);
            
        }
        jTable1.setModel(dtm);
        //load Độc giả
        ArrayList<DocGia> dsNXB=DocGiaDAO.layDanhSachDG();
        for(DocGia db:dsNXB){

            cbo_DocGia.addItem(db.toString());
        }
        cbo_DocGia.setSelectedIndex(-1);
    }
}
