/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import dao.NXBDAO;
import dao.SachDAO;
import dao.TacGiaDAO;
import dao.TheLoaiDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import pojo.ChiTietMT;
import pojo.NXB;
import pojo.Sach;
import pojo.TacGia;
import pojo.TheLoai;

/**
 *
 * @author Admin
 */
public class frSach extends javax.swing.JDialog {
public String ma;
    /**
     * Creates new form frSach
     */
    public frSach(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Sách");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setSize(1050, 600);
         this.setLocation(450, 300);
        btnLuu.setVisible(false);
        btnHuy.setVisible(false);
        lb_k1.setVisible(false);
        lb_k2.setVisible(false);
        lb_k3.setVisible(false);
        lb_k4.setVisible(false);
        lb_k5.setVisible(false);
        lb_k6.setVisible(false);
        lb_kt.setVisible(false);
        cbo_NXB.setEditable(true);
        cbo_TacGia.setEditable(true);
        cbo_TheLoai.setEditable(true);
        AutoCompleteDecorator.decorate(cbo_NXB);
        AutoCompleteDecorator.decorate(cbo_TacGia);
        AutoCompleteDecorator.decorate(cbo_TheLoai);
        hienthi();
        
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtTimSach = new javax.swing.JTextField();
        btnTimSach = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_MaSH = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNamXB = new javax.swing.JTextField();
        txtConLai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtTenSach = new javax.swing.JTextField();
        cbo_TheLoai = new javax.swing.JComboBox<>();
        cbo_TacGia = new javax.swing.JComboBox<>();
        cbo_NXB = new javax.swing.JComboBox<>();
        lb_k1 = new javax.swing.JLabel();
        lb_k2 = new javax.swing.JLabel();
        lb_k3 = new javax.swing.JLabel();
        lb_k4 = new javax.swing.JLabel();
        lb_k5 = new javax.swing.JLabel();
        lb_k6 = new javax.swing.JLabel();
        lb_kt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("DANH SÁCH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 80, 120, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sách", "Tên Sách", "Năm Xuất Bản"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 470, 220);
        getContentPane().add(txtTimSach);
        txtTimSach.setBounds(70, 32, 284, 30);

        btnTimSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_TimKiem.png"))); // NOI18N
        btnTimSach.setText("Tìm kiếm");
        btnTimSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSachActionPerformed(evt);
            }
        });
        getContentPane().add(btnTimSach);
        btnTimSach.setBounds(370, 30, 109, 40);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem);
        btnThem.setBounds(100, 360, 65, 25);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa);
        btnXoa.setBounds(340, 360, 55, 25);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jLabel9.setText("THÔNG TIN CHI TIẾT");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 10, 120, 16);

        jLabel2.setText("Mã Sách:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 50, 54, 16);
        jPanel1.add(lb_MaSH);
        lb_MaSH.setBounds(140, 50, 40, 20);

        jLabel4.setText("Mã Tác Giả:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 120, 69, 16);

        jLabel3.setText("Tên Sách:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 59, 16);

        jLabel6.setText("Mã NXB:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 160, 49, 16);

        jLabel5.setText("Mã Thể Loại:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 200, 75, 16);

        jLabel7.setText("Năm Xuất Bản:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 240, 100, 16);

        txtNamXB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamXBFocusLost(evt);
            }
        });
        jPanel1.add(txtNamXB);
        txtNamXB.setBounds(140, 240, 130, 22);

        txtConLai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConLaiFocusLost(evt);
            }
        });
        jPanel1.add(txtConLai);
        txtConLai.setBounds(140, 280, 130, 22);

        jLabel8.setText("Còn Lại:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 280, 60, 16);

        btnSua.setText("Cập nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);
        btnSua.setBounds(200, 330, 100, 25);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel1.add(btnLuu);
        btnLuu.setBounds(100, 330, 53, 25);

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuy);
        btnHuy.setBounds(310, 330, 60, 25);
        jPanel1.add(txtTenSach);
        txtTenSach.setBounds(140, 70, 280, 30);

        cbo_TheLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(cbo_TheLoai);
        cbo_TheLoai.setBounds(140, 200, 310, 22);

        cbo_TacGia.setToolTipText("");
        jPanel1.add(cbo_TacGia);
        cbo_TacGia.setBounds(140, 120, 310, 22);

        jPanel1.add(cbo_NXB);
        cbo_NXB.setBounds(140, 160, 310, 22);

        lb_k1.setForeground(new java.awt.Color(255, 51, 51));
        lb_k1.setText("(*)");
        jPanel1.add(lb_k1);
        lb_k1.setBounds(430, 70, 20, 20);

        lb_k2.setForeground(new java.awt.Color(255, 51, 51));
        lb_k2.setText("(*)");
        jPanel1.add(lb_k2);
        lb_k2.setBounds(460, 120, 18, 16);

        lb_k3.setForeground(new java.awt.Color(255, 0, 51));
        lb_k3.setText("(*)");
        jPanel1.add(lb_k3);
        lb_k3.setBounds(460, 160, 18, 16);

        lb_k4.setForeground(new java.awt.Color(255, 51, 51));
        lb_k4.setText("(*)");
        jPanel1.add(lb_k4);
        lb_k4.setBounds(460, 200, 18, 16);

        lb_k5.setForeground(new java.awt.Color(255, 0, 51));
        lb_k5.setText("(*)");
        jPanel1.add(lb_k5);
        lb_k5.setBounds(280, 240, 18, 16);

        lb_k6.setForeground(new java.awt.Color(255, 0, 51));
        lb_k6.setText("(*)");
        jPanel1.add(lb_k6);
        lb_k6.setBounds(280, 280, 18, 16);

        lb_kt.setForeground(new java.awt.Color(255, 51, 51));
        lb_kt.setText("(*):Bắt buộc");
        jPanel1.add(lb_kt);
        lb_kt.setBounds(200, 430, 160, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(530, 0, 500, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        ma= (String)jTable1.getValueAt(row, 0);
        Sach a=SachDAO.laySach(Integer.parseInt(ma));
        lb_MaSH.setText(a.getMaSH());
        txtTenSach.setText(a.getTenSH());
        txtNamXB.setText(a.getNamxb()+"");
        txtConLai.setText(a.getConlai()+"");
        //hiện cbo Thể Loại
        TheLoai c=TheLoaiDAO.layTL(Integer.parseInt(a.getMaTL()));
        cbo_TheLoai.setSelectedItem(c.toString());
        //hiện cbo Tác Giả
        TacGia tg=TacGiaDAO.layTG(Integer.parseInt(a.getMaTG()));
        cbo_TacGia.setSelectedItem(tg.toString());
        //hiện cbo NXB
        NXB nxb=NXBDAO.layNXB(Integer.parseInt(a.getMaNXB()));
        cbo_NXB.setSelectedItem(nxb.toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnTimSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSachActionPerformed
        // TODO add your handling code here:
        ArrayList<Sach> dsSach=SachDAO.timKiemSachTheoTen(txtTimSach.getText());
        DefaultTableModel atm=(DefaultTableModel)jTable1.getModel();
        atm.setRowCount(0);
        for(Sach db:dsSach){
            Vector<Object> vec=new Vector<Object>();
            vec.add(db.getMaSH());
            vec.add(db.getTenSH());
            vec.add(db.getNamxb());
            atm.addRow(vec);
            
        }
        jTable1.setModel(atm);
    }//GEN-LAST:event_btnTimSachActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtConLai.setText("");
        lb_MaSH.setText("");
        txtNamXB.setText("");
         
        txtTenSach.setText("");
        btnLuu.setVisible(true);
        btnHuy.setVisible(true);
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
        cbo_NXB.setSelectedIndex(-1);
        cbo_TacGia.setSelectedIndex(-1);
        cbo_TheLoai.setSelectedIndex(-1);
        lb_k1.setVisible(true);
        lb_k2.setVisible(true);
        lb_k3.setVisible(true);
        lb_k4.setVisible(true);
        lb_k5.setVisible(true);
        lb_k6.setVisible(true);
        lb_kt.setVisible(true);
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(txtTenSach.getText().equals("")||txtConLai.getText().equals("")||txtNamXB.getText().equals("")||cbo_NXB.getSelectedIndex()==-1||
                cbo_TheLoai.getSelectedIndex()==-1||cbo_TacGia.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ các thông tin bắt buộc");
        }
        else{
            int b=cbo_TheLoai.getSelectedIndex();
            int tg=cbo_TacGia.getSelectedIndex();
            int nxb=cbo_NXB.getSelectedIndex();
            Sach dg=new Sach(txtTenSach.getText(),cbo_TacGia.getItemAt(tg).toString().substring(cbo_TacGia.getItemAt(tg).toString().lastIndexOf(':')+1),
                   cbo_TheLoai.getItemAt(b).toString().substring(cbo_TheLoai.getItemAt(b).toString().lastIndexOf(':')+1),
                   cbo_NXB.getItemAt(nxb).toString().substring(cbo_NXB.getItemAt(nxb).toString().lastIndexOf(':')+1),Integer.parseInt(txtNamXB.getText()),Integer.parseInt(txtConLai.getText()));
            SachDAO.themSach(dg);
            txtConLai.setText("");
            lb_MaSH.setText("");
            txtNamXB.setText("");
            txtTenSach.setText("");
            cbo_NXB.setSelectedIndex(-1);
            cbo_TacGia.setSelectedIndex(-1);
            cbo_TheLoai.setSelectedIndex(-1);
            lb_k1.setVisible(false);
            lb_k2.setVisible(false);
            lb_k3.setVisible(false);
            lb_k4.setVisible(false);
            lb_k5.setVisible(false);
            lb_k6.setVisible(false);
            lb_kt.setVisible(false);
            //hiển thị các nút
            btnLuu.setVisible(false);
            btnHuy.setVisible(false);
            btnSua.setVisible(true);
            btnXoa.setVisible(true);
            hienthi();
            JOptionPane.showMessageDialog(this,"Thêm Thành Công");
        }
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()<1){
            JOptionPane.showMessageDialog(this,"hãy chọn Sách muốn xóa!");
        }
        else {
            int row=jTable1.getSelectedRow();
             ma= (String)jTable1.getValueAt(row, 0);

                  int tl=JOptionPane.showConfirmDialog(null,"bạn muốn xóa phải không","thông báo",JOptionPane.YES_NO_OPTION);
                    if(tl==JOptionPane.YES_OPTION){
                        SachDAO.xoaSach(Integer.parseInt(ma));
                        hienthi();
                        txtNamXB.setText("");
                        txtTenSach.setText("");
                        txtConLai.setText("");
                        lb_MaSH.setText("");
                        JOptionPane.showMessageDialog(this, "Xóa thành công");
                    }
                    else{
                        return;

             }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        //load thể loại
         // TODO add your handling code here:
        if(txtTenSach.getText().equals("")||txtConLai.getText().equals("")||txtNamXB.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ các thông tin bắt buộc");
        }
        else{
            int b=cbo_TheLoai.getSelectedIndex();
            int tg=cbo_TacGia.getSelectedIndex();
            int nxb=cbo_NXB.getSelectedIndex();
            Sach dg=new Sach(lb_MaSH.getText(),txtTenSach.getText(),cbo_TacGia.getItemAt(tg).toString().substring(cbo_TacGia.getItemAt(tg).toString().lastIndexOf(':')+1),
                    cbo_TheLoai.getItemAt(b).toString().substring(cbo_TheLoai.getItemAt(b).toString().lastIndexOf(':')+1),
                    cbo_NXB.getItemAt(nxb).toString().substring(cbo_NXB.getItemAt(nxb).toString().lastIndexOf(':')+1),Integer.parseInt(txtNamXB.getText()) ,Integer.parseInt(txtConLai.getText()));
            int tl=JOptionPane.showConfirmDialog(this, "bn có muốn cập nhật Sách có mã "+lb_MaSH.getText(), "thông báo", JOptionPane.YES_NO_OPTION);
            if(tl==JOptionPane.YES_OPTION){
               SachDAO.capNhatSach(dg);
               hienthi();

            }
            else return;
            //sau khi cập nhật vẫn hiện Thể loại
            Sach a=SachDAO.laySach(Integer.parseInt(lb_MaSH.getText()));
            int t=Integer.parseInt(a.getMaTL());
            TheLoai  x=TheLoaiDAO.layTL(t);
            cbo_TheLoai.setSelectedItem(x.toString());
            //sau khi cập nhật vẫn hiện Tác giả
            int t2=Integer.parseInt(a.getMaTG());
            TacGia  x2=TacGiaDAO.layTG(t2);
            cbo_TacGia.setSelectedItem(x2.toString());
            //sau khi cập nhật vẫn hiện NXB
            int t3=Integer.parseInt(a.getMaNXB());
            NXB  x3=NXBDAO.layNXB(t3);
            cbo_NXB.setSelectedItem(x3.toString());
        }
        
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        btnSua.setVisible(true);
        btnXoa.setVisible(true);
        btnHuy.setVisible(false);
        btnLuu.setVisible(false);
        txtConLai.setText("");
        lb_MaSH.setText("");
        lb_k1.setVisible(false);
        lb_k2.setVisible(false);
        lb_k3.setVisible(false);
        lb_k4.setVisible(false);
        lb_k5.setVisible(false);
        lb_k6.setVisible(false);
        lb_kt.setVisible(false);
        txtNamXB.setText("");
        //xóa item cbo
         cbo_NXB.setSelectedIndex(-1);
       cbo_TacGia.setSelectedIndex(-1);
       cbo_TheLoai.setSelectedIndex(-1);;
        txtTenSach.setText("");
    }//GEN-LAST:event_btnHuyActionPerformed

    private void txtNamXBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamXBFocusLost
        // TODO add your handling code here:
        if(txtNamXB.getText().equals("")!=true){
            try{
                
             double a=Double.parseDouble(txtNamXB.getText());
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Năm hợp lệ");
                txtNamXB.requestFocus();
                
            }
        }
    }//GEN-LAST:event_txtNamXBFocusLost

    private void txtConLaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConLaiFocusLost
        // TODO add your handling code here:
        if(txtConLai.getText().equals("")!=true){
            try{
                
             double a=Double.parseDouble(txtConLai.getText());
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng hợp lệ");
                txtConLai.requestFocus();
                
            }
        }
    }//GEN-LAST:event_txtConLaiFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frSach dialog = new frSach(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimSach;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbo_NXB;
    private javax.swing.JComboBox<String> cbo_TacGia;
    private javax.swing.JComboBox<String> cbo_TheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_MaSH;
    private javax.swing.JLabel lb_k1;
    private javax.swing.JLabel lb_k2;
    private javax.swing.JLabel lb_k3;
    private javax.swing.JLabel lb_k4;
    private javax.swing.JLabel lb_k5;
    private javax.swing.JLabel lb_k6;
    private javax.swing.JLabel lb_kt;
    private javax.swing.JTextField txtConLai;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTimSach;
    // End of variables declaration//GEN-END:variables

    private void hienthi() {
        ArrayList<Sach> dsSach=SachDAO.layDanhSachSach();
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        for(Sach db:dsSach){
            Vector<Object> vec=new Vector<Object>();
            vec.add(db.getMaSH());
            vec.add(db.getTenSH());
            vec.add(db.getNamxb());
            
            dtm.addRow(vec);
            
        }
        jTable1.setModel(dtm);
        //xóa item Trên Cbo
        cbo_TheLoai.removeAllItems();
        cbo_TacGia.removeAllItems();
        //load NXB
        ArrayList<NXB> dsNXB=NXBDAO.layDanhSachNXB();
        for(NXB db:dsNXB){

            cbo_NXB.addItem(db.toString());
        }
        cbo_NXB.setSelectedIndex(-1);
        //load thể loại 
        ArrayList<TheLoai> dsTL=TheLoaiDAO.layDanhSachTheLoai();
        for(TheLoai db:dsTL){
            cbo_TheLoai.addItem(db.toString());
        }
        cbo_TheLoai.setSelectedIndex(-1);
        //load Tác giả
        ArrayList<TacGia> dsTG=TacGiaDAO.layDanhSachTacGia();
        for(TacGia db:dsTG){

            cbo_TacGia.addItem(db.toString());
        }
        cbo_TacGia.setSelectedIndex(-1);
      
    }
}
