/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import dao.TacGiaDAO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.TacGia;

/**
 *
 * @author Admin
 */
public class frTacGia extends javax.swing.JDialog {

    /**
     * Creates new form frTacGia
     */
    public frTacGia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(1000, 600);
        this.setLocation(450, 300);
        btnLuu.setVisible(false);
        btnHuy.setVisible(false);
        lb_k1.setVisible(false);
        lb_k2.setVisible(false);
        hienthi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_ma = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtThongTin = new javax.swing.JTextArea();
        lb_k1 = new javax.swing.JLabel();
        lb_k2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_TimKiem.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel1.setText("DANH SÁCH TÁC GIẢ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã", "Tên"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton2)
                                .addGap(98, 98, 98)
                                .addComponent(btnXoa))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimKiem)))
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnXoa))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jLabel2.setText("THÔNG TIN CHI TIẾT");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(193, 25, 120, 16);

        jLabel3.setText("Mã:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 59, 22, 16);
        jPanel2.add(lb_ma);
        lb_ma.setBounds(159, 59, 44, 27);

        jLabel5.setText("Tên:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 111, 27, 16);

        jLabel6.setText("Thông tin:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 161, 59, 16);
        jPanel2.add(txtTen);
        txtTen.setBounds(159, 104, 208, 31);

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel2.add(btnLuu);
        btnLuu.setBounds(45, 442, 53, 25);

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel2.add(btnCapNhat);
        btnCapNhat.setBounds(162, 442, 83, 25);

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel2.add(btnHuy);
        btnHuy.setBounds(301, 442, 53, 25);

        txtThongTin.setColumns(20);
        txtThongTin.setRows(5);
        txtThongTin.setText("\n");
        jScrollPane2.setViewportView(txtThongTin);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(14, 195, 379, 216);

        lb_k1.setForeground(new java.awt.Color(255, 51, 51));
        lb_k1.setText("(*)");
        jPanel2.add(lb_k1);
        lb_k1.setBounds(372, 111, 31, 16);

        lb_k2.setForeground(new java.awt.Color(255, 0, 51));
        lb_k2.setText("(*):Bắt buộc");
        jPanel2.add(lb_k2);
        lb_k2.setBounds(174, 485, 72, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
         ArrayList<TacGia> dsSach=TacGiaDAO.timKiemTGTheoTen(txtTimKiem.getText());
        DefaultTableModel atm=(DefaultTableModel)jTable1.getModel();
        atm.setRowCount(0);
        for(TacGia db:dsSach){
            Vector<Object> vec=new Vector<Object>();
            vec.add(db.getMaTG());
            vec.add(db.getTenTG());
            
            atm.addRow(vec);
            
        }
        jTable1.setModel(atm);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int row=jTable1.getSelectedRow();
        String ma= (String)jTable1.getValueAt(row, 0);
        TacGia a=TacGiaDAO.layTG(Integer.parseInt(ma));
        lb_ma.setText(a.getMaTG());
        txtTen.setText(a.getTenTG());
        txtThongTin.setText(a.getGhiChu());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        lb_ma.setText("");
        txtTen.setText("");
        txtThongTin.setText("");
        lb_k1.setVisible(true);
        lb_k2.setVisible(true);
        btnLuu.setVisible(true);
       btnHuy.setVisible(true);
       btnCapNhat.setVisible(false);
       btnXoa.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(txtTen.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin bắt buộc");
        }
        else{
            TacGia dg=new TacGia(txtTen.getText(),txtThongTin.getText());
            TacGiaDAO.themTG(dg);
            lb_ma.setText("");
            txtTen.setText("");
            txtThongTin.setText("");  
            btnLuu.setVisible(false);
            btnHuy.setVisible(false);
            btnCapNhat.setVisible(true);
            btnXoa.setVisible(true);
            lb_k1.setVisible(false);
            lb_k2.setVisible(false);
            hienthi();
        }
        
       
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if(txtTen.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin bắt buộc");
        }
        else{
            TacGia dg=new TacGia(lb_ma.getText(),txtTen.getText(),txtThongTin.getText());
            int tl=JOptionPane.showConfirmDialog(this, "bn có muốn cập nhật TÁC GIẢ có mã "+lb_ma.getText(), "thông báo", JOptionPane.YES_NO_OPTION);
            if(tl==JOptionPane.YES_OPTION){
               TacGiaDAO.capNhatTG(dg);
            hienthi(); 
            }
            else return;
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        btnCapNhat.setVisible(true);
        btnXoa.setVisible(true);
        btnHuy.setVisible(false);
        btnLuu.setVisible(false);
        txtTen.setText("");
        txtThongTin.setText("");
        lb_ma.setText("");
        lb_k1.setVisible(false);
        lb_k2.setVisible(false);
    
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRowCount()<1){
            JOptionPane.showMessageDialog(this,"hãy chọn Tác giả muốn xóa!");
        }
        else {
            int row=jTable1.getSelectedRow();
            String ma= (String)jTable1.getValueAt(row, 0);

                  int tl=JOptionPane.showConfirmDialog(null,"bạn muốn xóa phải không","thông báo",JOptionPane.YES_NO_OPTION);
                    if(tl==JOptionPane.YES_OPTION){
                        TacGiaDAO.xoaTG(Integer.parseInt(ma));
                        hienthi();
                        JOptionPane.showMessageDialog(this,"Xóa thành công");
                        txtThongTin.setText("");
                        txtTen.setText("");
                    }
                    else{
                            return;
                        

             }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frTacGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frTacGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frTacGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frTacGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frTacGia dialog = new frTacGia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_k1;
    private javax.swing.JLabel lb_k2;
    private javax.swing.JLabel lb_ma;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextArea txtThongTin;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void hienthi() {
        ArrayList<TacGia> dsTG=TacGiaDAO.layDanhSachTacGia();
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        for(TacGia db:dsTG){
            Vector<Object> vec=new Vector<Object>();
            vec.add(db.getMaTG());
            vec.add(db.getTenTG());
            dtm.addRow(vec);
            
        }
        jTable1.setModel(dtm);
       
    }
    
}
