/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import java.awt.Frame;
import javax.swing.JOptionPane;
import pojo.QuanLi;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {
    private String maQL;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setTitle("Quản lí thư viện");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       
        this.setSize(1920,1000);
        this.mnuQuanLi.setEnabled(false);
        this.mnuDangXuat.setEnabled(false);
        
        this.mnuSach.setEnabled(false);
        this.mnuMuonTra.setEnabled(false);
        this.mnuDocGia.setEnabled(false);
        this.mnuTaiKhoan.setEnabled(false);
        lbSach.setVisible(false);
        lb_Sach2.setVisible(false);
        lb_Sach3.setVisible(false);
        lbGia.setVisible(true);
        lbGia2.setVisible(false);
        lb_bg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnDN = new javax.swing.JButton();
        lbSach = new javax.swing.JLabel();
        lb_Sach2 = new javax.swing.JLabel();
        lb_Sach3 = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        lbGia2 = new javax.swing.JLabel();
        lb_bg = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mnuDangNhap = new javax.swing.JMenuItem();
        mnuDangXuat = new javax.swing.JMenuItem();
        mnuThoat = new javax.swing.JMenuItem();
        mnuQuanLi = new javax.swing.JMenu();
        mnuSach = new javax.swing.JMenuItem();
        mnuMuonTra = new javax.swing.JMenuItem();
        mnuTacGia = new javax.swing.JMenuItem();
        mnuNXB = new javax.swing.JMenuItem();
        mnuDocGia = new javax.swing.JMenu();
        mnuTaiKhoan = new javax.swing.JMenu();
        mnuThongTin = new javax.swing.JMenuItem();
        mnuTaoTK = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mnuGioiThieu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÍ THƯ VIỆN");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(690, 40, 490, 70);

        btnDN.setBackground(new java.awt.Color(255, 0, 0));
        btnDN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDN.setText("ĐĂNG NHẬP");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        desktopPane.add(btnDN);
        btnDN.setBounds(830, 360, 180, 70);

        lbSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSach.setForeground(new java.awt.Color(204, 255, 255));
        lbSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2.jpg"))); // NOI18N
        lbSach.setText("SÁCH");
        lbSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSachMouseClicked(evt);
            }
        });
        desktopPane.add(lbSach);
        lbSach.setBounds(180, 310, 250, 210);

        lb_Sach2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_Sach2.setForeground(new java.awt.Color(0, 51, 255));
        lb_Sach2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4 (1).png"))); // NOI18N
        lb_Sach2.setText("TÁC GIẢ");
        lb_Sach2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_Sach2MouseClicked(evt);
            }
        });
        desktopPane.add(lb_Sach2);
        lb_Sach2.setBounds(1380, 280, 280, 270);

        lb_Sach3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_Sach3.setForeground(new java.awt.Color(204, 0, 0));
        lb_Sach3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5 (1).png"))); // NOI18N
        lb_Sach3.setText("MƯỢN SÁCH");
        lb_Sach3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_Sach3MouseClicked(evt);
            }
        });
        desktopPane.add(lb_Sach3);
        lb_Sach3.setBounds(810, 480, 310, 230);

        lbGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg3.jpg"))); // NOI18N
        desktopPane.add(lbGia);
        lbGia.setBounds(0, 0, 1920, 1270);

        lbGia2.setText("jLabel2");
        desktopPane.add(lbGia2);
        lbGia2.setBounds(601, 640, 450, 170);

        lb_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.jpg"))); // NOI18N
        desktopPane.add(lb_bg);
        lb_bg.setBounds(0, 0, 1920, 1270);

        mnuHeThong.setMnemonic('f');
        mnuHeThong.setText("Hệ Thống");

        mnuDangNhap.setMnemonic('o');
        mnuDangNhap.setText("Đăng nhập");
        mnuDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuDangNhapMouseClicked(evt);
            }
        });
        mnuDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangNhapActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuDangNhap);

        mnuDangXuat.setMnemonic('s');
        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuDangXuat);

        mnuThoat.setMnemonic('x');
        mnuThoat.setText("Thoát");
        mnuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThoatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mnuThoat);

        menuBar.add(mnuHeThong);

        mnuQuanLi.setMnemonic('e');
        mnuQuanLi.setText("Quản lí");
        mnuQuanLi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuQuanLiMouseClicked(evt);
            }
        });

        mnuSach.setMnemonic('t');
        mnuSach.setText("Sách");
        mnuSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSachMouseClicked(evt);
            }
        });
        mnuSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSachActionPerformed(evt);
            }
        });
        mnuQuanLi.add(mnuSach);

        mnuMuonTra.setMnemonic('y');
        mnuMuonTra.setText("Mượn trả");
        mnuMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuMuonTraMouseClicked(evt);
            }
        });
        mnuMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMuonTraActionPerformed(evt);
            }
        });
        mnuQuanLi.add(mnuMuonTra);

        mnuTacGia.setMnemonic('y');
        mnuTacGia.setText("Tác Giả");
        mnuTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuTacGiaMouseClicked(evt);
            }
        });
        mnuTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTacGiaActionPerformed(evt);
            }
        });
        mnuQuanLi.add(mnuTacGia);

        mnuNXB.setMnemonic('y');
        mnuNXB.setText("NXB");
        mnuNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNXBActionPerformed(evt);
            }
        });
        mnuQuanLi.add(mnuNXB);

        menuBar.add(mnuQuanLi);

        mnuDocGia.setMnemonic('h');
        mnuDocGia.setText("Độc Giả");
        mnuDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuDocGiaMouseClicked(evt);
            }
        });
        menuBar.add(mnuDocGia);

        mnuTaiKhoan.setMnemonic('h');
        mnuTaiKhoan.setText("Tài khoản");

        mnuThongTin.setMnemonic('s');
        mnuThongTin.setText("Thông tin");
        mnuThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuThongTinActionPerformed(evt);
            }
        });
        mnuTaiKhoan.add(mnuThongTin);

        mnuTaoTK.setMnemonic('s');
        mnuTaoTK.setText("Tạo Tài Khoản");
        mnuTaoTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTaoTKActionPerformed(evt);
            }
        });
        mnuTaiKhoan.add(mnuTaoTK);

        menuBar.add(mnuTaiKhoan);

        mnuThongKe.setMnemonic('h');
        mnuThongKe.setText("Thống kê");
        mnuThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuThongKeMouseClicked(evt);
            }
        });
        menuBar.add(mnuThongKe);

        mnuGioiThieu1.setMnemonic('h');
        mnuGioiThieu1.setText("Giới thiệu");
        menuBar.add(mnuGioiThieu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1685, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuThoatActionPerformed

    private void mnuDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangNhapActionPerformed
        // TODO add your handling code here:
        
        frmDangNhap a=new frmDangNhap(this,true);
        a.setVisible(true);
        
        if(a.isKq()!=null){

            maQL=a.isKq().getMaQL();
            this.mnuDangNhap.setEnabled(false);
            this.mnuQuanLi.setEnabled(true);
            this.mnuDangXuat.setEnabled(true);
            this.mnuSach.setEnabled(true);
            this.mnuMuonTra.setEnabled(true);
            this.mnuDocGia.setEnabled(true);
            this.mnuTaiKhoan.setEnabled(true);
            btnDN.setVisible(false);
            lbSach.setVisible(true);
            lb_Sach2.setVisible(true);
            lb_Sach3.setVisible(true);
            lb_bg.setVisible(true);
            lbGia.setVisible(false);
        }
        
    }//GEN-LAST:event_mnuDangNhapActionPerformed

    private void mnuDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDangNhapMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mnuDangNhapMouseClicked

    private void mnuSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSachActionPerformed
        // TODO add your handling code here:
        new frSach(this,false).setVisible(true);
    }//GEN-LAST:event_mnuSachActionPerformed

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        // TODO add your handling code here:
            this.mnuDangNhap.setEnabled(true);
            this.mnuQuanLi.setEnabled(false);
            this.mnuDangXuat.setEnabled(false);
            
            this.mnuSach.setEnabled(false);
            this.mnuMuonTra.setEnabled(false);
            this.mnuDocGia.setEnabled(false);
            this.mnuTaiKhoan.setEnabled(false);
            btnDN.setVisible(true);
            lbSach.setVisible(false);
            lb_Sach2.setVisible(false);
            lb_Sach3.setVisible(false);
             lb_bg.setVisible(false);
            lbGia.setVisible(true);
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void mnuMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMuonTraActionPerformed
        // TODO add your handling code here:
        new frMuonTra(this, false,maQL).setVisible(true);
    }//GEN-LAST:event_mnuMuonTraActionPerformed

    private void mnuDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuDocGiaMouseClicked
        // TODO add your handling code here:
        new frDocGia(this, false).setVisible(true);
    }//GEN-LAST:event_mnuDocGiaMouseClicked

    private void mnuThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuThongTinActionPerformed
        // TODO add your handling code here:
        new frTaiKhoan(this, true,maQL).setVisible(true);
    }//GEN-LAST:event_mnuThongTinActionPerformed

    private void mnuTaoTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTaoTKActionPerformed
        // TODO add your handling code here:
        new frThemTK(this,true).setVisible(true);
    }//GEN-LAST:event_mnuTaoTKActionPerformed

    private void mnuTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTacGiaActionPerformed
        // TODO add your handling code here:
        new frTacGia(this, true).setVisible(true);
    }//GEN-LAST:event_mnuTacGiaActionPerformed

    private void mnuNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNXBActionPerformed
        // TODO add your handling code here:
        new frNXB(this, true).setVisible(true);
    }//GEN-LAST:event_mnuNXBActionPerformed

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:
        mnuDangNhapActionPerformed(evt);
    }//GEN-LAST:event_btnDNActionPerformed

    private void lbSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSachMouseClicked
        // TODO add your handling code here:
        mnuSachMouseClicked(evt);
    }//GEN-LAST:event_lbSachMouseClicked

    private void mnuQuanLiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuQuanLiMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mnuQuanLiMouseClicked

    private void mnuSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSachMouseClicked
        // TODO add your handling code here:
         new frSach(this, true).setVisible(true);
    }//GEN-LAST:event_mnuSachMouseClicked

    private void lb_Sach3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_Sach3MouseClicked
        // TODO add your handling code here:
        mnuMuonTraMouseClicked(evt);
       
    }//GEN-LAST:event_lb_Sach3MouseClicked

    private void mnuMuonTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuMuonTraMouseClicked
        // TODO add your handling code here:
        new frMuonTra(this,false,maQL).setVisible(true);
    }//GEN-LAST:event_mnuMuonTraMouseClicked

    private void mnuTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTacGiaMouseClicked
        // TODO add your handling code here:
        new frTacGia(this,true).setVisible(true);
    }//GEN-LAST:event_mnuTacGiaMouseClicked

    private void lb_Sach2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_Sach2MouseClicked
        // TODO add your handling code here:
        mnuTacGiaMouseClicked(evt);
    }//GEN-LAST:event_lb_Sach2MouseClicked

    private void mnuThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuThongKeMouseClicked
        // TODO add your handling code here:
        new frThongKe(this, true).setVisible(true);
    }//GEN-LAST:event_mnuThongKeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDN;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbGia2;
    private javax.swing.JLabel lbSach;
    private javax.swing.JLabel lb_Sach2;
    private javax.swing.JLabel lb_Sach3;
    private javax.swing.JLabel lb_bg;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuDangNhap;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenu mnuDocGia;
    private javax.swing.JMenu mnuGioiThieu1;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenuItem mnuMuonTra;
    private javax.swing.JMenuItem mnuNXB;
    private javax.swing.JMenu mnuQuanLi;
    private javax.swing.JMenuItem mnuSach;
    private javax.swing.JMenuItem mnuTacGia;
    private javax.swing.JMenu mnuTaiKhoan;
    private javax.swing.JMenuItem mnuTaoTK;
    private javax.swing.JMenuItem mnuThoat;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenuItem mnuThongTin;
    // End of variables declaration//GEN-END:variables
    
}
